In [2]:
import numpy as np

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
a = np.array([1,2,3])

In [14]:
np.ones_like(a)

array([1, 1, 1])

In [16]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [24]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
np.random.uniform(0, 10, 3)

array([2.13095991, 5.02397342, 6.03560808])

In [44]:
x = np.array([1,2,3,2])

In [46]:
np.argmax(x)

2

In [50]:
x.argmax()

2

In [52]:
np.argmax([1,2,2,2])

1

In [56]:
x

array([1, 2, 3, 2])

In [58]:
x == 2

array([False,  True, False,  True])

In [60]:
np.where(x == 2)

(array([1, 3], dtype=int64),)

In [62]:
np.where(x == 2, 7, 13)

array([13,  7, 13,  7])

In [64]:
x

array([1, 2, 3, 2])

In [66]:
np.unique(x)

array([1, 2, 3])

In [68]:
np.unique(x, return_counts=True)

(array([1, 2, 3]), array([1, 2, 1], dtype=int64))

In [70]:
np.sort(x)

array([1, 2, 2, 3])

In [72]:
np.argsort(x)

array([0, 1, 3, 2], dtype=int64)

In [74]:
x

array([1, 2, 3, 2])

In [76]:
x[np.argsort(x)]

array([1, 2, 2, 3])

In [80]:
import os

In [82]:
os.path

<module 'ntpath' (frozen)>