In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
kik = np.full((3, 3), ".")
kik

array([['.', '.', '.'],
       ['.', '.', '.'],
       ['.', '.', '.']], dtype='<U1')

In [4]:
X.shape

(3, 4)

In [10]:
X[0,1]

2

In [12]:
X[1:3, 0:2]

array([[ 5,  6],
       [ 9, 10]])

In [14]:
X[2,:]

array([ 9, 10, 11, 12])

In [16]:
X[2]

array([ 9, 10, 11, 12])

In [18]:
X[:, 3]

array([ 4,  8, 12])

In [20]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
X.mean()

6.5

In [24]:
np.mean(X)

6.5

In [38]:
# średnia po kolumnach
X.mean(0)

array([5., 6., 7., 8.])

In [40]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
#średnia po wierszach
X.mean(1)

array([ 2.5,  6.5, 10.5])

In [44]:
X * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [48]:
Y = X * 10
Y

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [50]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
X + Y

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132]])

In [62]:
a = np.array([1 ,2 ,3, 4])
a

array([1, 2, 3, 4])

In [64]:
X + a

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [68]:
b = np.array([
    [100],
    [200],
    [300],
])
b

array([[100],
       [200],
       [300]])

In [70]:
b.shape

(3, 1)

In [74]:
X.shape

(3, 4)

In [76]:
X + b

array([[101, 102, 103, 104],
       [205, 206, 207, 208],
       [309, 310, 311, 312]])

In [80]:
X + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [88]:
X + np.array([1, 2, 3])

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [90]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
# max w karzdej kolumnie
X.max(0)

array([ 9, 10, 11, 12])

In [96]:
X / X.max(0)

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.55555556, 0.6       , 0.63636364, 0.66666667],
       [1.        , 1.        , 1.        , 1.        ]])

In [108]:
# X minus średnie w każdej kolumnie
print(X.mean(0))
X - X.mean(0)

[5. 6. 7. 8.]


array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [110]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [112]:
A.shape

(2, 3)

In [114]:
B.shape

(3, 2)

In [116]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [118]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [122]:
# transpozycja macierzy - zamiana wierszy z kolumnami
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [126]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
A.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
A.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [132]:
A.reshape(6, -1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [134]:
A.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
A.reshape(-1)

array([1, 2, 3, 4, 5, 6])