In [1]:
import numpy as np

In [3]:
list = [1,2,3,4]

In [5]:
np.array(list)

array([1, 2, 3, 4])

In [7]:
list_text = ["a", "b"]

In [9]:
np.array(list_text)

array(['a', 'b'], dtype='<U1')

In [11]:
list_text_2 = ["a", 1, True]

In [13]:
np.array(list_text_2)

array(['a', '1', 'True'], dtype='<U11')

In [15]:
x = np.array([0, 1, 2, 3, 4])

In [17]:
x[2]

2

In [19]:
x[-1]

4

In [21]:
x[1:3]

array([1, 2])

In [23]:
x[:2]

array([0, 1])

In [25]:
x[2:]

array([2, 3, 4])

In [27]:
x[[2,0,3]]

array([2, 0, 3])

In [29]:
x[np.array([2,0,3])]

array([2, 0, 3])

In [33]:
x[[True, False, True, False, True]]

array([0, 2, 4])

In [35]:
x[2] = 20

In [37]:
x

array([ 0,  1, 20,  3,  4])

In [39]:
x[2:4] = [200, 300]
x

array([  0,   1, 200, 300,   4])

In [41]:
x[1:4] = 1000
x

array([   0, 1000, 1000, 1000,    4])