In [1]:
import numpy as np

In [2]:
x = np.array([0, 1, 2, 3, 4])

In [3]:
y = np.array([0, 10, 20, 30, 40])

In [4]:
x + y

array([ 0, 11, 22, 33, 44])

In [5]:
x * y

array([  0,  10,  40,  90, 160])

In [6]:
x + 100

array([100, 101, 102, 103, 104])

In [7]:
x + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [14]:
# średnia różnica między elementami tablic x i y
print(np.abs(x - y))
np.mean(np.abs(x - y))

[ 0  9 18 27 36]


18.0

In [16]:
# suma kwadratów różnic
print((x - y)**2)
np.sum((x - y)**2)

[   0   81  324  729 1296]


2430

In [18]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [20]:
x

array([0, 1, 2, 3, 4])

In [22]:
np.power(x, 3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [24]:
np.power(x, np.array([2, 2, 3, 3, 0]))

array([ 0,  1,  8, 27,  1])

In [26]:
x > y

array([False, False, False, False, False])

In [28]:
x < y

array([False,  True,  True,  True,  True])

In [30]:
x > 2

array([False, False, False,  True,  True])

In [32]:
a = [0, 1, 2, 3, 4]

In [34]:
a > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [36]:
a, x

([0, 1, 2, 3, 4], array([0, 1, 2, 3, 4]))

In [38]:
x[x > 2]

array([3, 4])

In [40]:
np.sum(x[x > 2])

7

In [42]:
(x > 1) & (x < 3)

array([False, False,  True, False, False])

In [48]:
# ile elementów jest większych od 2
np.sum(x > 2)

2

In [50]:
len(x[x > 2])

2